# Generated by Django 3.0.4 on 2020-05-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donor',
            new_name='Donors',
        ),
    ]
