# Generated by Django 3.0.4 on 2020-05-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200519_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
